variable "ami-id" {}
variable "cluster_domain" {}
variable "kubelet_aci" {}
variable "kubelet_version" {}
variable "depends-id" {}
variable "dns_service_ip" {}
variable "etcd_ips" {}
variable "etcd-security-group-id" {}
variable "external-elb-security-group-id" {}
variable "instance-type" {}
variable "internal_tld" {}
variable "key-name" {}
variable "name" {}
variable "pod-ip-range" {}
variable "region" {}
variable "service-cluster-ip-range" {}
variable "subnet-ids-private" {}
variable "subnet-ids-public" {}
variable "vpc-id" {}
variable "k8s-apiserver-tar" {}
