#!/bin/bash

SELF=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -f1 -d'/')
PEERS=$(getent hosts minions.cncfdemo.k8s | awk '{ printf "%s ", $1 }')
MEMBERS=$(getent hosts minions.cncfdemo.k8s | wc -l)

/usr/local/bin/weave launch-router $WEAVE_ROUTER_ARGS --ipalloc-range 10.244.0.0/16 --ipalloc-init consensus=$MEMBERS ${PEERS#$SELF} 
