variable "name" { default = "test" }
variable "region" { default = "us-central1" }
variable "zone" { default = "us-central1-a" }
variable "project" { default = "test-163823" }
variable "cidr" { default = "10.0.0.0/16" }
variable "node_count" { default = "3" }
variable "node_version" { default = "1.6.2" }
variable "master_user" { default = "aoeui" }
variable "master_password" { default = "iueoadhtns"}
variable "vm_size" { default = "g1-small"}
