apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-v1
  labels:
    k8s-app: echo
spec:
  replicas: 2
  selector:
    k8s-app: echo
  template:
    metadata:
      labels:
        k8s-app: echo
    spec:
      nodeSelector:
        echo: "yes"
      containers:
      - name: echo
        image: zilman/echo:latest
        env:
        - name: GUNICORN_BIND
          value: 0.0.0.0:8000 
        ports:
        - containerPort: 8000
          name: gunicorn-local
          protocol: TCP
