variable "location" {}
variable "subnet-id" {}
variable "name" {}
variable "worker_vm_size" {}
variable "worker_node_count" {}
variable "image_publisher" {}
variable "image_offer"     {}
variable "image_sku"       {}
variable "image_version"   {}
variable "storage-account" {}
variable "storage-primary-endpoint" {}
variable "storage-container" {}
variable "availability-id" {}
variable "external-lb" {}
variable "cluster_domain" {}
variable "dns_service_ip" {}
variable "internal-tld" {}
variable "admin_username" {}
variable "k8s-worker-tar"  {}
variable "kubelet_image_url" {}
variable "kubelet_image_tag" {}
variable "cloud-config" {}
