variable "location" {}
variable "subnet-id" {}
variable "name" {}
variable "storage-account" {}
variable "storage-primary-endpoint" {}
variable "storage-container" {}
variable "availability-id" {}
variable "external-lb" {}
variable "cluster-domain" {}
variable "dns-service-ip" {}
variable "internal-tld" {}
variable "admin-username" {}
variable "k8s-worker-tar"  {}
variable "kubelet-image-url" {}
variable "kubelet-image-tag" {}
variable "cloud-config" {}
variable "worker-nodes" {}
