
apiVersion: v1
kind: ConfigMap
metadata:
  name: countly
data:
  api.js: |
      var countlyConfig = {
          
          mongodb: {
              host: "mongos.default",
              db: "countly",
              port: 27017,
              max_pool_size: 500,
          },
      
          api: {
              port: 3001,
              host: "localhost",
              max_sockets: 1024
          },
      
          path: "",
          logging: {
              info: ["jobs", "push"],
              default: "warn"
          }
      
      };
      
      module.exports = countlyConfig;
  frontend.js: |
      var countlyConfig = {
          
          mongodb: {
              host: "mongos.default",
              db: "countly",
              port: 27017,
              max_pool_size: 10,
          },
      
          web: {
              port: 6001,
              host: "localhost",
              use_intercom: true
          },
      
          path: "",
          cdn: ""
      
      };
      
      module.exports = countlyConfig;
  
